map_server: update to yaml-cpp 0.8.0
ros-navigation/navigation2 pull request #4267
Opened 2024-04-18 04:40 UTC by 981213

yaml-cpp 0.8.0 requires explicit linking against yaml-cpp::yaml-cpp.
This fixes building breakage on rolling due to https://github.com/ros2/yaml_cpp_vendor/pull/48

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | None |
| Primary OS tested on | Ubuntu 24.04 |
| Robotic platform tested on | Not yet. It shouldn't affect anything pratically. |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

* Fix building on rolling due to recent yaml-cpp upgrade

## Description of documentation updates required from your changes

None.

---

## Future work that may be required in bullet points
None.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2024-04-18 05:35 UTC, 981213 commented
The CI failed to build because it doesn't have the latest yaml_cpp_vendor package.

2024-04-21 18:49 UTC, SteveMacenski commented
@981213 should this PR wait then until that lands?

2024-04-21 18:50 UTC, SteveMacenski requested changes
Please follow up, I don't think this is an appropriate PR since we have the vendor. If the vendor needs to be updated, then update that and it'll be reflected here after a sync. Why are these changes needed here instead?

2024-04-21 18:50 UTC, SteveMacenski commented on nav2_map_server/CMakeLists.txt
> +find_package(yaml-cpp REQUIRED)
This should not be necessary, this is the role of the vendor package.

2024-04-21 18:50 UTC, SteveMacenski commented on nav2_map_server/CMakeLists.txt
> +  yaml-cpp::yaml-cpp)
Ditto and below

2024-04-22 02:18 UTC, 981213 commented
> should this PR wait then until that lands?

yaml_cpp_vendor 9.0.0 has been released into rolling, and that's how I noticed this problem. This is caused by the _vendor package update and independent of OS.

>  Why are these changes needed here instead - that breaks the vendorization?

This PR is created according to
https://github.com/ros2/yaml_cpp_vendor/pull/48#issuecomment-2046048236
and following:
https://github.com/ros-perception/image_common/pull/305
https://github.com/ros2/rviz/pull/1183
https://github.com/ros2/rosbag2/pull/1605

The solution provided upstream is to change all these downstream.

2024-04-22 04:28 UTC, 981213 commented
I agree that this change is a bit strange. Let me ask in that yaml-cpp update PR.

2024-04-22 15:26 UTC, SteveMacenski approved these changes

2024-04-22 15:27 UTC, SteveMacenski commented
Build has a number of complaints along the lines of 

```
CMake Error at CMakeLists.txt:32 (add_executable):
  Target "map_server" links to target "yaml-cpp::yaml-cpp" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

```

2024-04-23 04:27 UTC, 981213 commented
Oh, yaml_cpp_vendor 9.0 isn't available as binary package for jammy:
```
sudo apt-cache madison ros-rolling-yaml-cpp-vendor
ros-rolling-yaml-cpp-vendor | 8.3.1-1jammy.20240124.152723 | http://mirrors.ustc.edu.cn/ros2/ubuntu jammy/main amd64 Packages
```
```
sudo apt-cache madison ros-rolling-yaml-cpp-vendor
ros-rolling-yaml-cpp-vendor | 9.0.0-1noble.20240416.181051 | http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
```
This PR should be blocked until the switching to noble then.

2024-04-23 16:45 UTC, SteveMacenski commented
OK! I'll tag it that way with the 24.04 PR, thanks for the help and proactivity!

2024-04-23 18:08 UTC, SteveMacenski commented
Note to self that this is also a problem with Robot Localization to fix

2024-05-04 20:15 UTC, tonynajjar commented
I ran into the same issue and sunk 2 hours to fix it in a similar way,if only I found this PR beforehand :sweat_smile: Anyway, I think this should now be ready to be merged

2024-05-06 16:00 UTC, SteveMacenski commented
https://app.circleci.com/pipelines/github/ros-planning/navigation2/11466/workflows/31511139-b085-4f4b-ad71-5573452fa375/jobs/35332/steps

CI tells me this shouldn't happen until the 24.04 migration

2024-05-06 16:07 UTC, tonynajjar commented
Ah I tried it with the rolling docker images and there it was needed to work. I guess CI is not using latest rolling yet

2024-05-20 20:40 UTC, SteveMacenski commented
@981213 thanks for the contribution here - @tonynajjar is working on the full 24.04 migration which this commit was added to in https://github.com/ros-navigation/navigation2/pull/4298. So, I'm closing this as that PR supersedes with some other necessary changes. I want to thank you for your help here and responses! It is greatly appreciated - it all takes a village :-)

2024-05-20 20:40 UTC, closed without merging