fix(nav2_costmap_2d): make obstacle layer not current on enabled toggle
ros-navigation/navigation2 pull request #4507
Opened 2024-07-02 08:07 UTC by bektaskemal

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4465 |
| Primary OS tested on | Ubuntu|
| Robotic platform tested on | Turtlebot Sim|
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points
- Made obstacle layer consistent with other layers and make current false after enabled is toggled. So isCurrent function of costmap will return false and require update.

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2024-07-02 15:12 UTC, SteveMacenski requested changes
Did you test this to get the behavior we discussed?

2024-07-02 15:12 UTC, SteveMacenski commented on nav2_costmap_2d/plugins/obstacle_layer.cpp
> +      if (param_name == name_ + "." + "enabled" && enabled_ != parameter.as_bool()) {
Remove, we need to do all parameter updates, this would not allow you to enable it.

2024-07-02 15:13 UTC, SteveMacenski approved these changes

2024-07-03 09:08 UTC, bektaskemal commented
> Did you test this to get the behavior we discussed?

Yes, it works as we discussed.

2024-07-03 16:17 UTC, merged

2024-07-03 16:18 UTC, SteveMacenski commented
Thanks for the discussion / contribution!