Route Tool Rviz Panel
ros-navigation/navigation2 pull request #4775
Opened 2024-12-02 16:09 UTC by john-chrosniak

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NA |
| Primary OS tested on |Ubuntu |
| Robotic platform tested on | Gazebo turlebot simulation and Ackermann steering robot |
| Does this PR contain AI generated software? | Yes and it is marked inline in the code |

---

## Description of contribution in a few bullet points

* I added an Rviz panel to help create route graphs

## Description of documentation updates required from your changes

* Documentation needed to highlight how to use the new Rviz panel

---

## Future work that may be required in bullet points

* Could add support for bidirectional edges or adding route operations using the tool in future work

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2025-04-08 19:14 UTC, SteveMacenski commented on nav2_route/include/nav2_route/graph_saver.hpp
> +// Copyright (c) 2024 John Chrosniak
A big thing that we're missing in the graph saver and its associated plugin is unit testing for test coverage to make sure it works. Can you add in some tests to cover > 90% of the lines? 

Don't worry about the rviz plugin / panel, but the `nav2_route` saver and plugin should have testing done

2025-04-09 20:28 UTC, john-chrosniak commented on nav2_route/include/nav2_route/graph_saver.hpp
> +// Copyright (c) 2024 John Chrosniak
I just finished adding in tests for the graph saver and geojson saver plugin. Coverage for the graph saver is at 90% and coverage for the plugin is at 96%. Let me know if there's anything else I can help with!

2025-04-09 23:46 UTC, SteveMacenski commented on nav2_rviz_plugins/launch/route_tool.launch.py
> +#!/usr/bin/env python3
I think something in the preamble is formatted wrong, CI is failing that the license is not recognized. Did you copy paste this over and only replace your name? 

Maybe the python3 line needs to be removed?

2025-04-09 23:50 UTC, SteveMacenski commented on nav2_route/include/nav2_route/graph_saver.hpp
> +// Copyright (c) 2024 John Chrosniak
Can you write one more test to cover this case that is missing (just call the function with no `filepath` field when the param is set)?

```
  if (filepath.empty() && !graph_filepath_.empty()) {
    RCLCPP_DEBUG(
      logger_, "The graph filepath was not provided. "
      "Setting to %s", graph_filepath_.c_str());
    filepath = graph_filepath_;
  } 
```

Otherwise, LGTM, thanks for these!

2025-04-09 23:59 UTC, SteveMacenski commented
Question before I review on Friday: I noticed that you didn't modify the original server to have a service in the Route Server itself to save the graph to file. If we did that, we'd probably have to create services to also modify the graph by adding / removing a edge / node but then there's less logic that's happening in the rviz program itself that isn't portable to another GUI window. Can you say a little bit about why you did this all inline in the rviz tool? I assume you modify a bunch of stuff inline that is easier with direct access. I just want that in in mind when giving this a critical look  

Also: Does this dumping to file also do the `metadata` for the node semantics? Just checking.

2025-04-10 13:37 UTC, john-chrosniak commented on nav2_rviz_plugins/launch/route_tool.launch.py
> +#!/usr/bin/env python3
It looks like it may have been the use of single quotes instead of double quotes. I also removed the python3 line just in case.

2025-04-10 13:49 UTC, john-chrosniak commented
> Can you say a little bit about why you did this all inline in the rviz tool? 

My assumption was that route graphs are almost always going to be defined ahead of time, so there wasn't a need to support editing/saving graphs on the fly using the route server. The data structures used in the route tool class are only needed to keep track of nodes/edges as new elements are added/edited/removed, so if we're only modifying route graphs through this UI then this logic should be specific to the route tool.
 
> Also: Does this dumping to file also do the `metadata` for the node semantics? Just checking.

Yes both node and edge metadata is saved.

2025-04-11 17:34 UTC, SteveMacenski requested changes

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_route/include/nav2_route/graph_saver.hpp
> + * @brief An action server to save graph objects to a file
```suggestion
 * @brief An object to save graph objects to a file
```

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_route/src/plugins/graph_file_savers/geojson_graph_file_saver.cpp
> +    if (json_metadata.size()) {
```suggestion
    if (json_metadata.size() > 0) {
```

Just to be more explicit

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_route/src/plugins/graph_file_savers/geojson_graph_file_saver.cpp
> +    if (json_operations.size()) {
```suggestion
    if (json_operations.size() > 0) {
```

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_route/src/plugins/graph_file_savers/geojson_graph_file_saver.cpp
> +      if (json_metadata.size()) {
```suggestion
      if (json_metadata.size() > 0) {
```

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_route/src/plugins/graph_file_savers/geojson_graph_file_saver.cpp
> +      if (json_operations.size()) {
```suggestion
      if (json_operations.size() > 0) {
```

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_rviz_plugins/src/route_tool.cpp
> +  struct passwd pwd;
Its not clear to me what `pwd` `pw` `buf` or `homedir` is used for here. They don't appear to be used anywhere in the scope of this function

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_rviz_plugins/src/route_tool.cpp
> +  struct passwd pwd;
Ditto here

2025-04-11 17:34 UTC, SteveMacenski commented on nav2_rviz_plugins/src/route_tool.cpp
> +    if (graph_[graph_to_id_map_[node_id]].nodeid == node_id) {
The bits in this `if` statement are a little difficult for me to parse. I think what you're trying to do is handle the fact that a node was deleted from the vector so the various map lookup structures need adjustment. Is that right? 

If so, may I recommend rather than deleting the node from the vector, we simply set the graph's value of that node to something identifiable (just unpopulated constructor or ID of `max`) and when we go to save, before sending the `graph_` to the file saver, we check and delete any nodes that match that identifiable pattern.

2025-04-14 18:06 UTC, john-chrosniak commented on nav2_rviz_plugins/src/route_tool.cpp
> +  struct passwd pwd;
This was intended to get the path to the user's home directory to open up when loading/saving graphs. That variable was unused so the tool was instead defaulting to the current working directory. This is probably the preferred option since it will usually be the user's ROS 2 workspace, so I'll go ahead and remove this logic.

2025-04-14 18:06 UTC, john-chrosniak commented on nav2_rviz_plugins/src/route_tool.cpp
> +  struct passwd pwd;
Same comment as above, removing this block.

2025-04-14 18:07 UTC, john-chrosniak commented on nav2_rviz_plugins/src/route_tool.cpp
> +    if (graph_[graph_to_id_map_[node_id]].nodeid == node_id) {
Yes I agree this is a cleaner approach, just added in these changes.

2025-04-14 18:29 UTC, SteveMacenski approved these changes

2025-04-14 18:39 UTC, john-chrosniak commented
Awesome!!! I'm happy to help out with any fixes/maintenance needed as beta testers are brought on!

2025-04-14 19:12 UTC, merged

2025-04-14 19:12 UTC, SteveMacenski commented
Great, I appreciate it!