Use PoseStampedArray
ros-navigation/navigation2 pull request #4791
Opened 2024-12-11 10:42 UTC by tonynajjar

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |

---

## Description of contribution in a few bullet points

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2024-12-11 12:37 UTC, tonynajjar commented
@SteveMacenski as usual draft PR, before I spend more time on it can you confirm this is the direction we want to go in as discussed in https://github.com/ros-navigation/navigation2/pull/4771?

2024-12-11 19:17 UTC, SteveMacenski requested changes
Otherwise, no notes. Just docs for the migration guide and probably an FYI notification on Discourse/Slack would be good so folks expect it

2024-12-11 19:17 UTC, SteveMacenski commented on nav2_msgs/srv/GetCosts.srv
> +nav2_msgs/PoseStampedArray poses
Q: Does this one need to be changed? I don't mind it, but I view this more as the `path.poses` list as its usual use-case and I'm not sure I see the need for the header for this particular application

2024-12-12 09:32 UTC, tonynajjar commented on nav2_msgs/action/NavigateThroughPoses.action
Regarding what you mentioned [here](https://github.com/ros2/common_interfaces/pull/262#issuecomment-2536897202)

> we can have a stamp to gauge the age of the original request

Don't you mean gauge the age of the **goals computation**? To gauge the age of the actual **goal request**, I think we would need to add another top-level `Header`; otherwise you wouldn't be able to do it for `NavigateToPose`.

2024-12-12 19:34 UTC, SteveMacenski commented on nav2_msgs/action/NavigateThroughPoses.action
Yes, sorry, I was imprecise.

2025-01-02 08:30 UTC, tonynajjar commented
Happy new year! (ping in disguise @clalancette :smile: )

2025-01-07 08:43 UTC, tonynajjar commented on nav2_msgs/srv/GetCosts.srv
> +nav2_msgs/PoseStampedArray poses
agree

2025-01-07 09:03 UTC, tonynajjar commented on tools/underlay.repos
> +  ros/common_interfaces:
just for CI testing. Do you know when we can remove this? Are rolling binaries released nightly?

2025-01-07 13:05 UTC, tonynajjar commented
> Just docs for the migration guide

https://github.com/ros-navigation/docs.nav2.org/pull/630

>  FYI notification on Discourse/Slack would be good so folks expect it

Will do after the final review

2025-01-07 13:38 UTC, tonynajjar commented on nav2_msgs/action/ComputePathThroughPoses.action
> +geometry_msgs/PoseStampedArray goals
what do you think of renaming `goals` to `poses`?

2025-01-07 18:52 UTC, SteveMacenski commented on tools/underlay.repos
> +  ros/common_interfaces:
No, they are released monthlyish like other ROS distributions - it'll take a few weeks before we can remove it

2025-01-07 19:04 UTC, SteveMacenski requested changes
I'm generally noticing that the header stamp/frame isn't being populated in some places and I think it aught to be if we're going to be using it to check for updates. I believe that all things that populate a `PoseStampedArray` should have its `header` fully populated.

2025-01-07 19:04 UTC, SteveMacenski commented on nav2_simple_commander/nav2_simple_commander/robot_navigator.py
> +        goal_msg.goals.poses = goals
Should we populate the header stamp/frame?

2025-01-07 19:04 UTC, SteveMacenski commented on nav2_system_tests/src/system/nav_through_poses_tester_node.py
> +        goal_msg.poses.poses = [
Should we populate the stamp / frame?

2025-01-07 19:04 UTC, SteveMacenski commented on nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
> +        BT::InputPort<geometry_msgs::msg::PoseStampedArray>(
All the ports need to have their config docs updated for the change in type

2025-01-07 19:10 UTC, SteveMacenski commented on nav2_msgs/action/ComputePathThroughPoses.action
> +geometry_msgs/PoseStampedArray goals
I think `goals` is still a good enough name, but more I'm hesitant to change it since its used in so many places and its easy (especially w.r.t. the blackboard / BT XML / ports) to miss a few places or have users of new distributions have subtle breakages.

I'd leave it unless it was a serious bother. I still think navigating through poses' `poses` are themselves `goals`, just intermediate goals

2025-01-08 11:14 UTC, tonynajjar commented on nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
> +        BT::InputPort<geometry_msgs::msg::PoseStampedArray>(
I don't really see anywhere where `std::vector<geometry_msgs::msg::PoseStamped>` was specifically mentioned so that we need to change it. Can you point me more explicitly?

2025-01-08 11:29 UTC, tonynajjar commented on nav2_simple_commander/nav2_simple_commander/robot_navigator.py
> +        goal_msg.goals.poses = goals
sure but the stamp isn't really loyal to its definition if I set it to 'now'. I would need to pass the time the goals were computed in the function and that seems unnecessary currently

2025-01-08 11:31 UTC, tonynajjar commented on nav2_system_tests/src/system/nav_through_poses_tester_node.py
> +        goal_msg.poses.poses = [
same as above

2025-01-08 19:53 UTC, SteveMacenski commented on nav2_simple_commander/nav2_simple_commander/robot_navigator.py
> +        goal_msg.goals.poses = goals
This is the "simple" commander afterall, its not perfect in any regard :-)

2025-01-08 19:54 UTC, SteveMacenski approved these changes

2025-01-08 19:56 UTC, SteveMacenski commented on nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
> +        BT::InputPort<geometry_msgs::msg::PoseStampedArray>(
An example: https://docs.nav2.org/configuration/packages/bt-plugins/actions/ComputePathThroughPoses.html

Basically, any of the BT nodes you modified, you should be able to find the `goals` type within the BT XML config docs for that respective BT node

2025-01-09 16:43 UTC, tonynajjar commented on nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/compute_path_through_poses_action.hpp
> +        BT::InputPort<geometry_msgs::msg::PoseStampedArray>(
thanks, done in docs PR

2025-01-09 19:46 UTC, merged