Add acceleration limits to DriveOnHeading and BackUp behaviors
ros-navigation/navigation2 pull request #4810
Opened 2024-12-20 11:19 UTC by RBT22

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NA
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | own robot hardware |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points
 Added two params: `acceleration_limit` and `deceleration_limit` for DriveOnHeading and BackUp behaviors.

## Description of documentation updates required from your changes
Added new parameter, so need to add that to default configs and documentation page

---

## Future work that may be required in bullet points

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2024-12-20 17:05 UTC, SteveMacenski reviewed
Build is failing - not 100% sure why off hand other than it relates to a method added

2024-12-20 17:05 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +    last_vel_ = std::make_shared<double>(cmd_vel->twist.linear.x);
This is weird. If you want to initialize it so you know its valid, you could default it to `numerical_limits<double>::max()` and reset to that / check for it if we have a last value. I don't like this smart pointer stuff though

2024-12-20 17:05 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
I think the behaviors have a odom subscriber to use for the current velocity. 

This actually brings up a whole topic about whether we should base the velocity closed loop (on odom speed) or open looop (on the last command sent, assuming it was executed). We have this also topic in the controllers and velocity smoother. If we're adding in dynamic constraints here, I think its sensible we decide what makes sense here as well

2024-12-20 17:05 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +    if (acceleration_limit_ <= 0.0 && deceleration_limit_ <= 0.0) {
`||`? I assume we have to set both if we want to use either. That would let you remove the 2x `if` in the other branch as well. ALso we can simply if the `forward &&` to just `forward` and `!forward`

2024-12-20 17:05 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      bool forward = command_speed_ > 0.0 ? true : false;
```suggestion
      bool forward = command_speed_ > 0.0;
```

:wink:

2025-01-02 14:40 UTC, RBT22 commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
I couldn’t find the general odom subscriber —am I missing something? Should I add one just for this node, or would it make more sense to handle it across all the behaviors?

2025-01-07 19:47 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
Interesting, there's not one in the nav2_behaviors yet, I could have sworn there was one. 

I think that's a very sensible thing to add to the behavior server's scope, then pass to each of the behavior plugins to use if they see fit https://github.com/ros-navigation/navigation2/blob/main/nav2_behaviors/src/behavior_server.cpp#L132-L137

2025-01-07 19:49 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
But it also depends if we want to do closed-loop control here or open-loop, assuming that velocities sent are velocities executed. Before going too far down that rabbit hole, do you think open-looped control like what you have now (velocity out = velocity executed) is sensible enough for your needs? I think it very well might be considering the nature of it

2025-01-07 19:49 UTC, SteveMacenski commented
Sorry for the delayed review - see comment above

2025-01-07 19:53 UTC, SteveMacenski requested changes

2025-01-07 19:53 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      rclcpp::ParameterValue(0.0));
Better defaults please - see the velocity smoother and use its defaults

2025-01-07 19:53 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +
remove line L173 space

2025-01-07 19:53 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +          cmd_vel->twist.linear.x = max_vel_to_stop;
I think you may also need to set a minimum velocity parameter. Most robots can't go 1mm/s or have stalling velocities.

2025-01-07 19:53 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +          cmd_vel->twist.linear.x = max_vel_to_stop;
Speaking of this -- an aside. Do you use the rotation shim controller? Right now, we don't do the deceleration as a function of its target orientation and this would be great to add in there too if you happened to also use it & be open to submitting the PR

2025-01-08 13:58 UTC, RBT22 commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
Actually, this way works fine for us. I originally tried it with closed-loop control but ended up switching to open-loop, and it’s been working well.

2025-01-09 00:34 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double current_speed = last_vel_ ? *last_vel_ : 0.0;
OK - we can leave it as open loop then :-) 

See other review comments below

2025-01-10 14:53 UTC, RBT22 commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +          cmd_vel->twist.linear.x = max_vel_to_stop;
@SteveMacenski I can add the limits for the shim controller after this, but I’m kinda stuck on the tests—can’t get the subscriber to run its callback. Any tips?

2025-01-11 01:39 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      rclcpp::ParameterValue(0.01));
```suggestion
      rclcpp::ParameterValue(0.10));
```

More realistic

2025-01-11 01:40 UTC, SteveMacenski reviewed
Also, configuration guide entries are needed and migration guide to mention the new params

2025-01-11 01:40 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      rclcpp::ParameterValue(0.01));
Also for the nav2_params.yaml

2025-01-11 01:43 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +          cmd_vel->twist.linear.x = max_vel_to_stop;
Is cmd_vel the right topic name? It generally looks right ot me, but I'd look at other subscription-based BT node tests for reference :-)

2025-01-16 11:39 UTC, RBT22 commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +          cmd_vel->twist.linear.x = max_vel_to_stop;
Thanks for the feedback! I looked through the repo but couldn’t find any other subscription-based BT node tests—maybe I missed them? I’ve tried the steps you mentioned, but I’m not sure how to check the topic. Could you give me some guidance or point me to an example?

2025-01-22 12:12 UTC, RBT22 commented
Hi @SteveMacenski,

I’ve been looking into the testing setup, and I believe I might have misunderstood it initially. If I’m interpreting this correctly now, the tests for the behaviors themselves are part of the nav2_system_tests package. Is that correct?

If so, I’ll need to edit the backup_tester.py and drive_tester.py scripts to incorporate the acceleration checks.

Thanks for your guidance!

2025-01-23 02:35 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      cmd_vel->twist.linear.x = command_speed_;
Add an `RCLCPP_INFO_ONCE` that accel/decel limits were not set

2025-01-23 02:35 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +    node->get_parameter(this->behavior_name_ + ".minimum_speed", minimum_speed_);
Check after this to force the accel/decel to be positive/negative. That will save users some headaches

2025-01-23 02:35 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double min_feasible_speed = current_speed + deceleration_limit_ / this->cycle_frequency_;
What if the `current_speed` is negative? If you have asymmetric acceleration and deceleration limits (i.e. `-1.0, 2.5`) then the 'accelerating backward' will be deceleration and `decelerating backward` will be acceleration

2025-01-23 02:36 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double min_feasible_speed = current_speed + deceleration_limit_ / this->cycle_frequency_;
(we have this issue in MPPI too, so its an easy thing to miss https://github.com/ros-navigation/navigation2/issues/4601)

2025-01-23 02:39 UTC, SteveMacenski commented
> If I’m interpreting this correctly now, the tests for the behaviors themselves are part of the nav2_system_tests package. Is that correct?

Yes!

2025-01-24 16:08 UTC, RBT22 commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      double min_feasible_speed = current_speed + deceleration_limit_ / this->cycle_frequency_;
Thanks for pointing that out! I didn’t miss this, though—if you think about it in physical terms, velocity has direction, so when moving backward, the negative deceleration limit can actually reduce the rate at which speed increases. I tried to reflect that in the docs. But if the convention in the repo is to treat the limits without direction, I’m happy to adjust.

2025-01-27 20:09 UTC, SteveMacenski requested changes
With these + the documentation updates on docs.nav2.org, I can merge this!

2025-01-27 20:09 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +      throw std::runtime_error{"Invalid parameter: acceleration_limit or deceleration_limit"};
If we're going to throw, we need to catch here [1] and return false to the lifecycle transition. I think though you can just fix the sign setting silently, but I'm also OK with this way as well 

[1] https://github.com/ros-navigation/navigation2/blob/6e1c85eba70ed9800b69886c15d73268d60f46e9/nav2_behaviors/src/behavior_server.cpp#L98

2025-01-27 20:09 UTC, SteveMacenski commented on nav2_behaviors/include/nav2_behaviors/plugins/drive_on_heading.hpp
> +    if (acceleration_limit_ < 0.0 || deceleration_limit_ > 0.0) {
```suggestion
    if (acceleration_limit_ <= 0.0 || deceleration_limit_ >= 0.0) {
```

From your recent changes without supporting non-accel/decel setting, they must be non-zero in order to move at all

2025-01-28 20:20 UTC, SteveMacenski approved these changes

2025-01-28 20:21 UTC, merged

2025-01-28 20:21 UTC, SteveMacenski commented
@RBT22 thank you alot for jumping in and implementing this!