fix simple smoother failing during final approach
ros-navigation/navigation2 pull request #4817
Opened 2024-12-24 19:33 UTC by rayferric

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #4710 |
| Primary OS tested on | Ubuntu (osrf/ros:jazzy-desktop-full) |
| Robotic platform tested on | my own custom simulated robot  |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

* modified smoother server's simple_smoother plugin to not throw FailedToSmoothPath when the robot is approaching the end of path

I can alter this behavior if requested. My only requirement for this patch is that no error will be thrown when the path is ending and the last and only segment is too short to be processed, causing `segments_smoothed` to be zero.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

2025-01-02 19:19 UTC, SteveMacenski approved these changes
Seems very sensible / a good idea

2025-01-02 19:20 UTC, SteveMacenski commented
@rayferric two things:
1. There's a CI test failing from this change. I think you just need to set the size of the path > 1 as an input for an exception that should be thrown
2. Please sign your commits with DCO (see the job failure below)

Then I can merge!

2025-01-03 16:24 UTC, rayferric commented
CI failed due to unrelated errors in TF2@rolling:

![image](https://github.com/user-attachments/assets/27174d5b-2123-4513-b51c-0daeefa72275)

I have pushed an unrelated commit, [use tf2's .hpp includes](https://github.com/ros-navigation/navigation2/pull/4817/commits/f4799fddd231fbdc3f888879986b6b3d49655fb7), in order to see if the CI will go through.

2025-01-03 21:37 UTC, rayferric commented
Okay, I've removed the extra commit and rebase-merged the changes from main. Now let's wait until https://github.com/ros-navigation/navigation2/pull/4732 is merged.

2025-01-04 01:14 UTC, SteveMacenski commented
Rebase with https://github.com/ros-navigation/navigation2/pull/4823 for CI

2025-01-04 01:15 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> +  if (!success) {
Is this necessary?

2025-01-04 13:10 UTC, rayferric commented on nav2_smoother/src/simple_smoother.cpp
> +  if (!success) {
In order to introduce the least changes necessary, I can remove this modification and modify the tests to use a two-segment path like you suggested.

To explain why those changes were made in the first place, I've noticed that smoother server expects the plugin to return false when the time limit is reached, see:
https://github.com/ros-navigation/navigation2/blob/3763f78d6cf8ed6b4559eb04034891dcf439a41e/nav2_smoother/src/nav2_smoother.cpp#L289-L303

I case of simple smoother, `success` tells whether all calls to `smoothImpl()` returned true:
https://github.com/ros-navigation/navigation2/blob/3763f78d6cf8ed6b4559eb04034891dcf439a41e/nav2_smoother/src/simple_smoother.cpp#L98-L99

And `smoothImpl()` returns true either when either a collision is detected or iteration limit was reached:
https://github.com/ros-navigation/navigation2/blob/3763f78d6cf8ed6b4559eb04034891dcf439a41e/nav2_smoother/src/simple_smoother.cpp#L139-L146
https://github.com/ros-navigation/navigation2/blob/3763f78d6cf8ed6b4559eb04034891dcf439a41e/nav2_smoother/src/simple_smoother.cpp#L184-L192

If time limit is reached, `smoothImpl()` throws an exception, which is out of order since it does not cause smooth() to return false, and instead unwinds the stack:
 https://github.com/ros-navigation/navigation2/blob/3763f78d6cf8ed6b4559eb04034891dcf439a41e/nav2_smoother/src/simple_smoother.cpp#L151-L158
 
My modification would partly reduce this inconsistency by not returning false for reasons unrelated to time limit. This fixes the two failing tests, which expect `FailedToSmoothPath` to be thrown in both cases when 1. collision is found or 2. iteration limit is reached respectively (this for a single-segment path).
 
I could modify the code further to properly handle all cases, by catching the timeout exception in `smooth()` loop and returning false when the exception was caught in any call to `smoothImpl()`.

2025-01-04 17:01 UTC, rayferric commented
Here, I rebased with `depreciate_c_headers2`. Now waiting for your decision regarding the test failures

2025-01-07 01:25 UTC, SteveMacenski commented
Rebase on main, it was merged in with some other fixes

2025-01-07 01:28 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> +  if (!success) {
> I could modify the code further to properly handle all return cases, by catching the timeout exception in smooth() loop and returning false when the exception was caught in any call to smoothImpl().

I would prefer that, thank you! These were retrofits on the original software when we added in the contextual error code return types. You've found somewhere we created a gap that would be good to fill! :-)

2025-01-07 19:42 UTC, SteveMacenski requested changes
I think there are a couple of bugs that need to be addressed, but generally looks good to me once resolved. They're pretty small.

2025-01-07 19:42 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> -  bool success = true, reversing_segment;
Reversing segment is indeed used. The `impl` method has that as a `bool &` which is modified in `updateApproximatePathOrientations`.

2025-01-07 19:42 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> +  return true;
This never checks if `success` like we did before, which is OK, but then we need to compare `segments_attempted == segments_smoothed` to tell if `success` criteria works.

Or, simply leave the success computation and `return success`. Either way

2025-01-08 11:09 UTC, rayferric commented on nav2_smoother/src/simple_smoother.cpp
> -  bool success = true, reversing_segment;
`updateApproximatePathOrientations` resets it to false on entry, and the value left there after return is not used outside of this function

2025-01-08 11:15 UTC, rayferric commented on nav2_smoother/src/simple_smoother.cpp
> +  return true;
The server expects `smooth()` to return whether the timeout was reached (and optionally to throw an exception if a fatal failure is encountered):

https://github.com/ros-navigation/navigation2/blob/43d7f7e309e782f1e277191ff414c98b9ac4f51c/nav2_smoother/src/nav2_smoother.cpp#L289-L301

Pure virtual `smooth()`'s docstring says the same thing:

https://github.com/ros-navigation/navigation2/blob/43d7f7e309e782f1e277191ff414c98b9ac4f51c/nav2_core/include/nav2_core/smoother.hpp#L69-L78

2025-01-09 02:18 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> +  return true;
I think the case of max iterations reached is also breaking a limit where false is returned [1]. Regardless of what the doc strings say, this change introduces a gap. If we smooth everything; we do the right thing. If we smooth nothing; we do the right thing. If we partially smooth, we're not capturing that case in a return or error condition. This is what the previous PR's `success` state measured. If anything, we should update the doc string to be less specific about "time" but rather a "limit" being breached. Time and iteration limits are similar in contextual meaning - we've exceeded application limits  

[1] https://github.com/ros-navigation/navigation2/blob/e1742adc4bf1dd5eb4808f1b29927779de680f62/nav2_smoother/src/simple_smoother.cpp#L149-L154

2025-01-12 19:45 UTC, rayferric commented
Hey, in order for us to easily resolve this PR, I've reverted my intrusive changes and fixed the tests so that they pass. Is that alright?

2025-01-13 21:00 UTC, SteveMacenski approved these changes

2025-01-13 21:01 UTC, SteveMacenski commented on nav2_smoother/src/simple_smoother.cpp
> +  if (segments_smoothed == 0 && path_segments.size() > 1) {
```suggestion
  if (segments_smoothed == 0 && path_segments.size() > 0) {
```

No?

2025-01-13 21:59 UTC, rayferric commented on nav2_smoother/src/simple_smoother.cpp
> +  if (segments_smoothed == 0 && path_segments.size() > 1) {
Not quite. The original code fixes the basic case of approach by disabling errors when there's just one path segment. If the segment has less than 9 verts, segments_smoothed is 0 and without this condition, the smoothing fails. Though this fix will not work in the case of two segments, if both of them have below 9 vertices, etc.

Suggested fix that would account for the 2+ segment edge case:

I can add back the attempted_segments counter and check if attempted > 1, so that the "no path segments smoothed" would appear whenever at least one segment was long enough to attempt smoothing, but no segments were actually smoothed.

This would also allow me to roll back the changes I made to test cases

2025-01-14 00:25 UTC, SteveMacenski commented
I'm going back to the original ticket to remind myself what we were trying to accomplish since we've gone down a few directions. This code has clearly degraded a bit over time and various contributions and refactoring over its lifetime and I want to think about this more abstractly to what we want to do: final path approaches working well and knowing that path segments in various directions can be of arbitrary length.

I think we need to make a few changes here. The returns for `smoothImpl` and when we throw are a bit crazy - as you point out. 

Within `smoothImpl`:
- I think the collision failure case should set `path = last_path`, update the orientations, and return true. If we're mid-execution, then the previous is known to be collision free & that's as good as we can do. If its the first iteration and the path is already in collision, then we can't do much here. If the user cares, then they'd have `goal->check_for_collisions` set in which the finally validated path would then throw the path in collision error [in the main Smoother Server](https://github.com/ros-navigation/navigation2/blob/main/nav2_smoother/src/nav2_smoother.cpp#L306C9-L327)
- For this specific type of smoother, we can return a semi-smoothed path (others if not converged are not going to be valid, like those from the Constrained Smoother). So, for `its >= max_its_` I think we can warn log and return true. 
- For maximum duration, I think we can leave that alone as throwing since that's an actual exit failure

Within `smooth()`:
- Now, all returns from `smoothImpl` are throwing or `return true`, so we don't need to pay much attention to the return bool anymore. I think we can remove the `segments_smoothed` and success logic. And we can change the `smoothImpl` to be a `void` type.
- That would also imply removing the potential to throw `FailedToSmoothPath`, but looking at the git blame for that, it seems haphazardly implemented ([along with the rest of the issues we're removing in this thread](https://github.com/ros-navigation/navigation2/pull/3296))

---

I also reviewed `savitzky_golay_smoother.cpp` to see what changes I wanted to make to be aligned with this to fix other potential messy locations. That one looks good to me and does what I basically just suggested.

2025-01-17 16:48 UTC, rayferric commented
Thanks for the review and your well thought out suggestions! Thanks to them, preparing this commit was a breeze. I'm happy that you decided to remove the overly restrictive error handling. As a bonus, I have included a test case for the end-of-path approach scenario, so that my original issue doesn't reoccur.

2025-01-21 23:56 UTC, SteveMacenski approved these changes
Sorry that this was such a painful review and iteration process, I promise it'll be better in the future :wink:

2025-01-21 23:57 UTC, merged